import { promises as fs } from "node:fs";
import path from "node:path";

type BroadcastTransaction = {
  contractAddress?: string;
  contractName?: string;
  transactionType?: string;
};

type BroadcastFile = {
  chain?: number;
  timestamp?: number;
  transactions?: BroadcastTransaction[];
  returns?: {
    mscMarketV1?: {
      value?: string;
    };
  };
};

type DeploymentRecord = {
  contractName: "MscMarketV1";
  chainId: number;
  chainName: string;
  address: string;
  proxyAddress: string;
  implementationAddress: string | null;
  deployedAt: string | null;
  deploymentTimestamp: number | null;
  source: string;
};

const CHAIN_NAMES: Record<number, string> = {
  31337: "Anvil Local",
  5167003: "MXC Testnet",
  18686: "MXC Mainnet",
};

async function readJson<T>(filePath: string): Promise<T> {
  const content = await fs.readFile(filePath, "utf8");
  return JSON.parse(content) as T;
}

function toIsoTimestamp(timestamp?: number) {
  return timestamp ? new Date(timestamp * 1000).toISOString() : null;
}

function formatDeploymentRecord(
  chainId: number,
  source: string,
  broadcast: BroadcastFile,
): DeploymentRecord | null {
  const transactions = broadcast.transactions ?? [];
  const implementationTx = transactions.find(
    (tx) => tx.contractName === "MscMarketV1" && tx.transactionType === "CREATE",
  );
  const proxyTx = transactions.find(
    (tx) =>
      tx.contractName === "ERC1967Proxy" && tx.transactionType === "CREATE",
  );

  const proxyAddress =
    broadcast.returns?.mscMarketV1?.value ?? proxyTx?.contractAddress ?? null;

  if (!proxyAddress) {
    return null;
  }

  return {
    contractName: "MscMarketV1",
    chainId,
    chainName: CHAIN_NAMES[chainId] ?? `Chain ${chainId}`,
    address: proxyAddress,
    proxyAddress,
    implementationAddress: implementationTx?.contractAddress ?? null,
    deployedAt: toIsoTimestamp(broadcast.timestamp),
    deploymentTimestamp: broadcast.timestamp ?? null,
    source,
  };
}

async function collectFoundryDeployments(repoRoot: string) {
  const deployRoot = path.join(
    repoRoot,
    "foundry",
    "broadcast",
    "DeployMscMarketV1.s.sol",
  );

  const entries = await fs.readdir(deployRoot, { withFileTypes: true });
  const deployments: DeploymentRecord[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const chainId = Number(entry.name);
    if (Number.isNaN(chainId)) continue;

    const runLatestPath = path.join(deployRoot, entry.name, "run-latest.json");

    try {
      const broadcast = await readJson<BroadcastFile>(runLatestPath);
      const deployment = formatDeploymentRecord(chainId, runLatestPath, broadcast);
      if (deployment) {
        deployments.push(deployment);
      }
    } catch (error) {
      console.warn(`Skipping ${runLatestPath}:`, error);
    }
  }

  return deployments.sort((left, right) => left.chainId - right.chainId);
}

function buildGeneratedModule(abi: unknown, deployments: DeploymentRecord[]) {
  const deploymentEntries = deployments
    .map((deployment) => {
      const implementationAddress = deployment.implementationAddress
        ? `"${deployment.implementationAddress}" as Address`
        : "null";
      const deployedAt = deployment.deployedAt ? `"${deployment.deployedAt}"` : "null";
      const deploymentTimestamp =
        deployment.deploymentTimestamp === null
          ? "null"
          : String(deployment.deploymentTimestamp);

      return `  ${deployment.chainId}: {
    contractName: "${deployment.contractName}",
    chainId: ${deployment.chainId},
    chainName: "${deployment.chainName}",
    address: "${deployment.address}" as Address,
    proxyAddress: "${deployment.proxyAddress}" as Address,
    implementationAddress: ${implementationAddress},
    deployedAt: ${deployedAt},
    deploymentTimestamp: ${deploymentTimestamp},
    source: "${deployment.source.replaceAll("\\", "\\\\")}",
  },`;
    })
    .join("\n");

  return `// This file is auto-generated by scripts/sync-contracts-to-web.ts.
// Do not edit it by hand.

import type { Abi, Address } from "viem";

export const MSC_MARKET_ABI = ${JSON.stringify(abi, null, 2)} as const satisfies Abi;

export const MSC_MARKET_DEPLOYMENTS = {
${deploymentEntries}
} as const;

export type MscMarketDeployment =
  (typeof MSC_MARKET_DEPLOYMENTS)[keyof typeof MSC_MARKET_DEPLOYMENTS];
`;
}

async function main() {
  const webRoot = process.cwd();
  const repoRoot = path.resolve(webRoot, "..");
  const abiPath = path.join(repoRoot, "foundry", "abis", "MscMarketV1.json");
  const outputPath = path.join(
    webRoot,
    "src",
    "lib",
    "contracts",
    "generated",
    "msc-market.ts",
  );

  const abi = await readJson<unknown>(abiPath);
  const deployments = await collectFoundryDeployments(repoRoot);

  if (deployments.length === 0) {
    throw new Error("No Foundry deployment artifacts were found.");
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, buildGeneratedModule(abi, deployments), "utf8");

  console.log(
    `Synced ${deployments.length} deployment(s) to ${path.relative(webRoot, outputPath)}`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
