// Auto-generated by scripts/sync-contract-address.js
// Do not edit manually.

export const CONTRACT_ADDRESSES = {
  mscMarketV1: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707",
} as const;

export const MSC_MARKET_V1_ADDRESS = CONTRACT_ADDRESSES.mscMarketV1;
